# Example: How to use the reusable label-sync workflow in your repo
#
# Place this file in: .github/workflows/label-sync.yml
# Replace YOUR_ORG with your GitHub organization name

name: Label Management

on:
  push:
    branches:
      - main
    paths:
      - '.github/labels.yml'
  workflow_dispatch:

jobs:
  sync-labels:
    uses: YOUR_ORG/shopify-reusable-workflows/.github/workflows/label-sync.yml@main
    # Optional inputs (these are the defaults):
    # with:
    #   config-file: '.github/labels.yml'
    #   delete-other-labels: false
