# Example: How to use the reusable Shopify Theme CI/CD workflow in your repo
#
# Place this file in: .github/workflows/shopify-theme-ci.yml

name: Shopify Theme CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, labeled, unlabeled]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  shopify-ci:
    uses: MeekcoAsia/shopify-reusable-workflows/.github/workflows/shopify-theme-ci.yml@main

    # Optional: Customize versions and features (these are the defaults)
    # with:
    #   node-version: '20'
    #   ruby-version: '3.1'
    #   run-theme-check: true
    #   run-validation: true

# Note: GITHUB_TOKEN is automatically passed to reusable workflows
# Remember: Developers should include the Shopify preview theme link in the PR description
